version: 28.0.4

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environments:
    - MONGO_INITDB_ROOT_USERNAME=admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
    - /mnt/FDrive/CommandsForLinux/DockerCommands/DockerVolume:/data/db

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environments:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=qwerty
      ME_CONFIG_MONGODB_URL: "mongodb://admin:qwerty@mongo:27017"


